"""Spatial analysis pipeline for neuron clustering and heatmap generation.

Ported from the swc-mapper repository, adapted to use BrainGlobe Atlas API
instead of Allen SDK.
"""

from .clustering import (
    ClusterExclusionRule,
    ClusterRegionFilter,
    ClusterRegionRule,
    ClusterRegionSelection,
    ClusterResult,
    ClusterRunMetadata,
    cluster_somas_dbscan,
    cluster_somas_hierarchical,
    cluster_somas_kmeans,
    compute_clustermap_data,
    compute_linkage,
    compute_linkage_from_condensed,
)
from .correlation import (
    compute_pearson_correlation_matrix,
    correlation_long_to_matrix,
)
from .heatmap import build_node_counts_volume
from .mask import (
    build_binary_mask_from_heatmap,
    build_binary_mask_from_threshold_range,
    dilate_mask_to_volume_increase,
    get_expanded_region_voxel_ids,
    get_expanded_region_voxel_ids_for_regions,
    get_region_mask,
    get_regions_mask,
    isolate_heatmap_volume_to_region_ids,
    merge_heatmap_volumes,
    otsu_threshold_positive,
    smooth_heatmap_volume,
)
from .region_filter import (
    PreparedClusterRegionFilter,
    prepare_cluster_region_filter,
)
from .region_profile import (
    RegionalProfileAtlas,
    RegionProfileBuildCancelled,
    RegionProfileInspection,
    RegionProfileMetadata,
    RegionProfileValidationError,
    build_hierarchy_closure,
    build_region_profile,
    inspect_region_profile,
    register_region_profile,
)
from .region_query import (
    AllOf,
    AnyOf,
    NeuriteIntersects,
    Not,
    QueryLaterality,
    QueryScope,
    RegionalMeasurement,
    RegionalThreshold,
    RegionQueryEngine,
    RegionQueryResult,
    RegionReference,
    RegionSelection,
    SomaIn,
    ThresholdComparison,
    deserialize_query,
    serialize_query,
)
from .search import VoxelSearchRequest, VoxelSearchResult, compute_voxel_search
from .voxel_filter import (
    DendriteLabelCoverage,
    PreparedVoxelNodeFilter,
    VoxelNodeFilter,
    query_dendrite_label_coverage,
)

__all__ = [
    "AllOf",
    "AnyOf",
    "ClusterExclusionRule",
    "ClusterRegionFilter",
    "ClusterRegionRule",
    "ClusterRegionSelection",
    "ClusterResult",
    "ClusterRunMetadata",
    "DendriteLabelCoverage",
    "NeuriteIntersects",
    "Not",
    "PreparedClusterRegionFilter",
    "PreparedVoxelNodeFilter",
    "QueryLaterality",
    "QueryScope",
    "RegionProfileBuildCancelled",
    "RegionProfileInspection",
    "RegionProfileMetadata",
    "RegionProfileValidationError",
    "RegionQueryEngine",
    "RegionQueryResult",
    "RegionReference",
    "RegionSelection",
    "RegionalMeasurement",
    "RegionalProfileAtlas",
    "RegionalThreshold",
    "SomaIn",
    "ThresholdComparison",
    "VoxelNodeFilter",
    "VoxelSearchRequest",
    "VoxelSearchResult",
    "build_binary_mask_from_heatmap",
    "build_binary_mask_from_threshold_range",
    "build_hierarchy_closure",
    "build_node_counts_volume",
    "build_region_profile",
    "cluster_somas_dbscan",
    "cluster_somas_hierarchical",
    "cluster_somas_kmeans",
    "compute_clustermap_data",
    "compute_linkage",
    "compute_linkage_from_condensed",
    "compute_pearson_correlation_matrix",
    "compute_voxel_search",
    "correlation_long_to_matrix",
    "deserialize_query",
    "dilate_mask_to_volume_increase",
    "get_expanded_region_voxel_ids",
    "get_expanded_region_voxel_ids_for_regions",
    "get_region_mask",
    "get_regions_mask",
    "inspect_region_profile",
    "isolate_heatmap_volume_to_region_ids",
    "merge_heatmap_volumes",
    "otsu_threshold_positive",
    "prepare_cluster_region_filter",
    "query_dendrite_label_coverage",
    "register_region_profile",
    "serialize_query",
    "smooth_heatmap_volume",
]
